# Generated by Django 4.0.1 on 2022-01-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='data',
            field=models.CharField(max_length=200),
        ),
    ]
