# Generated by Django 4.0.1 on 2022-01-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
